version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_PROJECT_URL=${VITE_SUPABASE_PROJECT_URL}
      - VITE_SUPABASE_API_KEY=${VITE_SUPABASE_API_KEY}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
      - VITE_GOOGLE_MAPS_ID=${VITE_GOOGLE_MAPS_ID}
      - VITE_TOLLGURU_API_KEY=${VITE_TOLLGURU_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - PORT=5000
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  notifications:
    build:
      context: ./notifications
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3000"
    depends_on:
      - redis
    networks:
      - app-network

  smtp:
    image: namshi/smtp
    environment:
      - RELAY_HOST=smtp.example.com
      - RELAY_PORT=587
      - RELAY_USERNAME=your_username
      - RELAY_PASSWORD=your_password
    ports:
      - "25:25"
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge