version: "3.8"
services:
  node:
    image: "node:current"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: "sh run.sh"
    networks:
      - backend

  notifications:
    build:
      context: ./notifications
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - backend

  smtp:
    image: namshi/smtp
    environment:
      - RELAY_HOST=smtp.example.com
      - RELAY_PORT=587
      - RELAY_USERNAME=your_username
      - RELAY_PASSWORD=your_password
    ports:
      - "25:25"
    networks:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge